# Generated by Django 5.1.7 on 2025-03-13 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_area_reels_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
