# Generated by Django 5.1.7 on 2025-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_area_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='property_type',
            field=models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk', '5 BHK'), ('villa', 'Villa'), ('penthouse', 'Penthouse'), ('studio', 'Studio Apartment')], default='2bhk', max_length=20),
        ),
    ]
