# Generated by Django 5.1.7 on 2025-03-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reels_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reels',
            name='property_type',
            field=models.CharField(choices=[('flat', 'FLAT'), ('villa', 'VILLA'), ('house', 'HOUSE'), ('studio', 'STUDIO'), ('farm', 'FARM'), ('penthouse', 'Penthouse'), ('apartment', 'Apartment')], default='flat', max_length=20),
        ),
    ]
