# Generated by Django 5.1.7 on 2025-03-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('villa', 'Villa'), ('flat', 'Flat'), ('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('office', 'Office')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('tags', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('preferred_property_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.reel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.user')),
            ],
        ),
    ]
