# Generated by Django 5.1.7 on 2025-03-17 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_location_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.location'),
        ),
    ]
