# Generated by Django 5.1.7 on 2025-03-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0004_area_reel_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_property_type',
            field=models.CharField(choices=[('villa', 'Villa'), ('flat', 'Flat'), ('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('office', 'Office')], max_length=50),
        ),
    ]
